functionsGradleVersion = 0.15.0
functionsTypescriptRuntimeVersion = 0.190.0
functionsTypescriptVersion = 0.1089.0
nodeInstallationVersion = 22.21.1
repositoryName = Functions
repositoryOrg = inmind.ai
repositoryProject = Temporary Training Artifacts
repositoryRid = ri.stemma.main.repository.d0e35fab-0de2-459c-81fa-9e6eb22b3a32
