canEnforceMinimumPythonVersion = true
condaSolveImplementation = hawk
enableCodeAssistEnvironmentCaching = true
enableLegacyFallback = false
envPackingLogicVersion = 2
modelsPluginVersion = 0.1379.0
org.gradle.caching = true
org.gradle.vfs.watch = false
palantirModelsVersion = 0.2113.0
pipelineOverrideUuid = 02885fb748574e0aa0a510334bfce089
rootProjectName = IPO_ml_code_repo
systemProp.http.connectionTimeout = 600000
systemProp.http.socketTimeout = 600000
systemProp.org.gradle.internal.http.connectionTimeout = 600000
systemProp.org.gradle.internal.http.socketTimeout = 600000
transformsDefaultBranchName = master
transformsLangPythonPluginVersion = 1.1114.0
transformsRepoOrg = inmind.ai
transformsRepoPath = /inmind.ai/Temporary Training Artifacts/Learning - Peter El Bikai/Final Project/code repos/IPO_ml_code_repo
transformsRepoProject = Temporary Training Artifacts
transformsRepoRid = ri.stemma.main.repository.58b62e69-fbc5-4012-ac3d-c035e0d6cad1
transformsVersion = 10.97.0
useCondaLocksForPlatforms = linux-64
useDefaultPython = false
useHawkAsDefaultSolver = true
useHawkUvSolver = true
useIncrementalSolve = true
